export const categoryList = [
  {
    id: 1,
    value: "House",
    label: " House",
  },
  {
    id: 2,
    value: "Apartament",
    label: "Apartament",
  },
  {
    id: 3,
    value: "Villa",
    label: "Villa",
  },
];

export const ratingList = [
  {
    id: 1,
    value: "1",
    label: "1🌟",
  },
  {
    id: 2,
    value: "2",
    label: "2🌟",
  },
  {
    id: 3,
    value: "3",
    label: "3🌟",
  },
  {
    id: 4,
    value: "4",
    label: "4🌟",
  },
  {
    id: 5,
    value: "5",
    label: "5🌟",
  },
];

export const dataList = [
  {
    id: 1,
    title: "Elton House",
    category: "Villa",
    country: "america",
    rating: 5,
    address: '32 Pawnee Street Butte',
    price: 2500,
    coverSrc: "./images/places/house1lg.png",
  },
  {
    id: 2,
    title: "Icy House",
    category: "House",
    country: "india",
    address: '84 Woodland St. Cocoa',
    rating: 4,
    price: 1000,
    coverSrc: "./images/places/house2lg.png",
  },
  {
    id: 3,
    title: "Blue Lodge",
    category: "Apartament",
    country: "china",
    address: '28 Westport Dr. Warminster',
    rating: 3,
    price: 2000,
    coverSrc:"./images/places/house3lg.png",
  },
  {
    id: 4,
    title: "Cherry End",
    category: "Apartament",
    country: "america",
    address: '32 Pawnee Street Butte',
    rating: 1,
    price: 1800,
    coverSrc: "./images/places/house4lg.png",
  },
  {
    id: 5,
    title: "Ivylands",
    category: "Villa",
    country: "india",
    address:"45 wolf street",
    rating: 5,
    price: 2000,
    coverSrc: "./images/places/house5lg.png",
  },
  {
    id: 6,
    title: "West End",
    country: "china",
    address: '28 Westport Dr. Warminster',
    category: "House",
    rating: 5,
    price: 3500,
    coverSrc:"./images/places/house6lg.png",
  },
  {
    id: 7,
    title: "Meadowside",
    category: "House",
    country: "america",
    rating: 2,
    address: '32 Pawnee Street Butte',
    price: 2200,
    coverSrc: "./images/places/house7lg.png",
  },
  {
    id: 8,
    title: "Rabbit's End",

    category: "Apartament",
    country: "india",
    address: '28 Westport Dr. Warminster',
    rating: 1,
    price: 1900,
    coverSrc:"./images/places/house8lg.png",
  },
  {
    id: 9,
    title: "The Ivies",
    category: "Villa",
    country: "china",
    address: '32 Pawnee Street Butte',
    rating: 4,
    price: 2750,
    coverSrc: "./images/places/house9lg.png",
  },
  {
    id: 10,
    title: "The Old School",
    category: "House",
    address: '28 Westport Dr. Warminster',
    country: "america",
    rating: 2,
    price: 4350,
    coverSrc: "./images/places/house10lg.png",
  },
  {
    id: 11,
    title: "Nippy House",
    category: "Apartament",
    address: '28 Westport Dr. Warminster',
    country: "india",
    rating: 3,
    price: 3300,
    coverSrc: "./images/places/house11lg.png",
  },
  {
    id: 12,
    title: "River View",
    category: "House",
    country: "china",
    address: '32 Pawnee Street Butte',
    rating: 2,
    price: 4100,
    coverSrc: "./images/places/house12lg.png",
  },
];
